# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Octopus Carnival
email: u.alberton@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A repository of my English language RPG-related writings.
  Mostly GURPS with a smattering of other systems.
baseurl: "/octopus-carnival" # the subpath of your site, e.g. /blog
url: "https://bira.github.io" # the base hostname & protocol for your site
twitter:
  username: mestre_bira
github_username:  Bira
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
paginate: 5
disqus:
  shortname: 'octopus-carnival'
google_analytics: UA-85001601-1
# Build settings
markdown: kramdown
theme: minima
