name: Build and deploy a Jekyll site to github pages

on:
  push:
    branches:
      - main

jobs:
  jekyll:
    runs-on: ubuntu-22.04
    steps:
      - name: folder setup
        uses: actions/checkout@v7

      - name: setup ruby
        uses: ruby/setup-ruby@v1.316.0
        with:
          ruby-version: 3.4

      - name: install dependencies & build site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true

      - name: deploy
        uses: peaceiris/actions-gh-pages@v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          enable_jekyll: false
